branches:
  - main

name-template: 'Version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

sort-by: title # sort alphabetically
sort-direction: ascending

categories:
  - title: '### NEW:'
    labels:
      - 'pr/feature'
  - title: '### FIXED:'
    labels:
      - 'pr/bug-fix'
  - title: '### IMPROVED:'
    labels:
      - 'pr/enhancement'
      - 'pr/optimization'
  - title: '### CHANGED:'
    labels:
      - 'pr/cleanup'
      - 'pr/change'
  - title: '### SETTINGS:'
    labels:
      - 'pr/setting'
  - title: '### TRANSLATIONS:'
    labels:
      - 'pr/translation'
  - title: '### DOCUMENTATION:'
    labels:
      - 'pr/documentation'

exclude-labels:
  - 'ignore-changelog'
  - 'tools'

change-template: '* $TITLE (#$NUMBER) by $AUTHOR'
template: |
  _Requires [CBA_A3](https://github.com/CBATeam/CBA_A3) and [ACE3](https://github.com/acemod/ACE3)._

  ## Summary

  ## Changelog

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

# PRs with the label target/next-arma trigger a bump of the Major version
# most others trigger a bump of the Minor version
# PRs with the label pr/bug-fix trigger a bump of the Patch version
version-resolver:
  major:
    labels:
      - "target/next-arma"
  minor:
    labels:
      - "pr/feature"
      - "pr/cleanup"
      - "pr/change"
      - "pr/enhancement"
      - "pr/optimization"
      - "pr/setting"
      - 'pr/translation'
  patch:
    labels:
      - "pr/documentation"
      - "pr/bug-fix"
  default: patch

replacers:
  # Category titles
  # Release Drafter automatically makes the category as ## Heading
  # and we want them as ### Heading
  - search: '/\#\# (\#\#\# (NEW|FIXED|IMPROVED|CHANGED|SETTINGS|TRANSLATIONS|DOCUMENTATION):)/g'
    replace: '$1'
