site_name: Tactical Tarps Documentation
site_description: Documentation for Tactical Tarps Mod for Arma 3
site_url: https://tacticaltrainingteam.github.io/tactical-tarps/

repo_url: https://github.com/TacticalTrainingTeam/tactical-tarps
repo_name: TacticalTrainingTeam/tactical-tarps
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: tt_icon.png
  favicon: tt_favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.path
    - navigation.indexes
    - content.action.edit
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - privacy
  - search

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - abbr
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home: index.md
  - Common:
      - Overview: common/index.md
      - API Functions: common/api.md
      - Events: common/events.md
      - Settings: common/settings.md
  - Drone:
      - Overview: drone/index.md
      - Settings: drone/settings.md
  - Hazmat:
      - Overview: hazmat/index.md
      - Settings: hazmat/settings.md
  - Medic:
      - Overview: medic/index.md
      - Settings: medic/settings.md
  - Repair:
      - Overview: repair/index.md
      - Settings: repair/settings.md
  - Signal:
      - Overview: signal/index.md
      - Settings: signal/settings.md
  - Contributing: contributing.md
  - License: license.md
