name            = "Tactical Tarps";                    // Name of your mod
author            = "Tactical Tarps Team";                // Affects Arma 3 Launcher, when the mod are loaded as local
logo            = "img\tt_icon.paa";            // Logo displayed in the main menu
logoOver        = "img\tt_icon.paa";    // When the mouse is over, in the main menu
tooltip            = "Tactical Tarps";
tooltipOwned    = "by Tactical Tarps Team";                // Tool tip displayed when the mouse is left over, in the main menu
picture            = "img\tt_logo.paa";        // Picture displayed from the expansions menu. Optimal size is 2048x1024
actionName        = "GitHub";
action            = "https://github.com/TacticalTrainingTeam/tactical-tarps";            // Website URL, that can be accessed from the expansions menu
overview        = "Provides tactical tarps for signalling and utility.";    // Supports structured text
hideName        = 0;                        // Hide the extension name
hidePicture        = 0;                        // Hide the extension menu
dlcColor[]        = { 0.23, 0.39, 0.30, 1 };    // Color used for DLC stripes and backgrounds (RGBA)
logoSmall        = "img\tt_icon.paa";        // Display in creative lists, next to the entities added by the mod
