name = "Tactical Tarps"
author = "Tactical Tarps Team"
prefix = "tt"
mainprefix = "z"

[files]
include = [
    "meta.cpp",
    "mod.cpp",
    "authors.txt",
    "LICENSE",
    "/img/*.paa",
    "*.bikey"
]

[version]
# path = "addons/main/script_version.hpp" # Default
# major = 0 # Overrides path when set
# minor = 1
# patch = 1
git_hash = 0 # Default: 8
