name: Upload Release

on:
  release:
    types: [ "published" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v7

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Build Mod
        run: hemtt release

      - name: Upload full version to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/tt-latest.zip
          asset_name: tt-${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true